# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LinkedinFireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LinkedinFireBase

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'SDWebImage'
pod 'Firebase/Database'

  target 'LinkedinFireBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LinkedinFireBaseUITests' do
    # Pods for testing
  end

end
